version: "3"
services:
  mongo-express_0:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb_0:27017/
  mongodb_0:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root    
    container_name: "mongodb_0"
    ports:
      - "27017:27017"
#  mongo-express_1:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8082:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb_1:27018/
#  mongodb_1:
#    image: mongo:4
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    container_name: "mongodb_1"
#    ports:
#      - "27018:27017"
#  mongo-express_2:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8083:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb_2:27017/
#  mongodb_2:
#    image: mongo:4
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    container_name: "mongodb_2"
#    ports:
#      - "27019:27017"
#  redis_0:
#    image: "bitnami/redis:latest"
#    container_name: "redis_0"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"
#  cassandra_0:
#    image: cassandra:latest
#    container_name: "cassandra_0"
#    ports:
#      - "7000:7000"
#  cassandra_1:
#    image: cassandra:latest
#    container_name: "cassandra_1"
#    ports:
#      - "7001:7000"